### ISSUE TITLE
Input must be oneliners

### ISSUE THREAD

**Issue by k9ne257** [k9ne257/Droidgramm#21]

**Comment by ppppppatrick** [comment]
was soll ich machen

**Comment by k9ne257** [comment]
Alle edittext Felder in der Repository müssen nur aus einer Input Zeile Bestehen. Die müssen das Attribut 'android:maxLines="1" ' haben

**Comment by k9ne257** [comment]
Bist du schon durch @ppppppatrick

**Comment by victorien09** [comment]
ja wohl
